#include "Station.h"

#include "ComControl.h"

namespace wiphynlcontrol {

Station::Station(const uint32_t &id)
    : Entity(),
      dev_index_(&get_attribute(dev_index_),
                 NL80211_ATTR_IFINDEX,
                 Attribute::ValueTypes::UINT32,
                 NL80211_CMD_GET_STATION,
                 NL80211_CMD_UNSPEC),
      // Private Properties.
      sta_info_(&get_attribute(dev_index_),
                NL80211_ATTR_STA_INFO,
                Attribute::ValueTypes::NESTED,
                NL80211_CMD_UNSPEC,
                NL80211_CMD_UNSPEC),
      tx_bitrate_info_(&get_attribute(dev_index_),
                static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_TX_BITRATE),
                Attribute::ValueTypes::NESTED,
                NL80211_CMD_UNSPEC,
                NL80211_CMD_UNSPEC,
                &get_attribute(sta_info_)),
      rx_bitrate_info_(&get_attribute(dev_index_),
                static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_RX_BITRATE),
                Attribute::ValueTypes::NESTED,
                NL80211_CMD_UNSPEC,
                NL80211_CMD_UNSPEC,
                &get_attribute(sta_info_)),
      info_bss_param_(&get_attribute(dev_index_),
                static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_BSS_PARAM),
                Attribute::ValueTypes::NESTED,
                NL80211_CMD_UNSPEC,
                NL80211_CMD_UNSPEC,
                &get_attribute(sta_info_)),
      // Public Properties.
      mac_addr_(&get_attribute(dev_index_),
                NL80211_ATTR_MAC,
                Attribute::ValueTypes::UINT48,
                NL80211_CMD_GET_STATION,
                NL80211_CMD_UNSPEC),
      // Nested in sta_info_.
      inactive_time_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_INACTIVE_TIME),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      rx_bytes_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_RX_BYTES),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      tx_bytes_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_TX_BYTES),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      rx_packets_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_RX_PACKETS),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      tx_packets_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_TX_PACKETS),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      beacon_rx_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_BEACON_RX),
            Attribute::ValueTypes::UINT64,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      info_signal_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_SIGNAL),
            Attribute::ValueTypes::INT8,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      info_offset_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_T_OFFSET),
            Attribute::ValueTypes::UINT64,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      tx_retries_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_TX_RETRIES),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      tx_failed_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_TX_FAILED),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      beacon_loss_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_INFO_BEACON_LOSS),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(sta_info_)),
      // Nested in tx_bitrate_info_.
      tx_bitrate_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_RATE_INFO_BITRATE32),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(tx_bitrate_info_)),
      // Nested in rx_bitrate_info_.
      rx_bitrate_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_RATE_INFO_BITRATE32),
            Attribute::ValueTypes::UINT32,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(rx_bitrate_info_)),
      // Nested in info_bss_param_.
      short_preamble_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_BSS_PARAM_SHORT_PREAMBLE),
            Attribute::ValueTypes::FLAG,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(info_bss_param_)),
      short_slot_time_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_BSS_PARAM_SHORT_SLOT_TIME),
            Attribute::ValueTypes::FLAG,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(info_bss_param_)),
      beacon_interval_(&get_attribute(dev_index_),
            static_cast<Nl80211AttributeTypes>(NL80211_STA_BSS_PARAM_BEACON_INTERVAL),
            Attribute::ValueTypes::UINT16,
            NL80211_CMD_GET_STATION,
            NL80211_CMD_UNSPEC,
            &get_attribute(info_bss_param_)),
      all_attrs({&get_attribute(mac_addr_),
                 &get_attribute(inactive_time_),
                 &get_attribute(rx_bytes_),
                 &get_attribute(tx_bytes_),
                 &get_attribute(rx_packets_),
                 &get_attribute(tx_packets_),
                 &get_attribute(beacon_rx_),
                 &get_attribute(info_signal_),
                 &get_attribute(info_offset_),
                 &get_attribute(tx_retries_),
                 &get_attribute(tx_failed_),
                 &get_attribute(beacon_loss_),
                 &get_attribute(tx_bitrate_),
                 &get_attribute(rx_bitrate_),
                 &get_attribute(short_preamble_),
                 &get_attribute(short_slot_time_),
                 &get_attribute(beacon_interval_),
                 }) {
  set_identifier(id);
}  // namespace wiphynlcontrol

void Station::get() {
  const auto attr_args =
      std::vector<const Attribute *>{&get_attribute(dev_index_)};
  const std::vector<Attribute *> attrs(all_attrs.begin(), all_attrs.end());
  ComControl::get_communicator().challenge(
      NL80211_CMD_GET_STATION, Message::Flags::DUMP, &attr_args, &attrs);
}

uint32_t Station::get_identifier() const {
  return dev_index_.value_;
}

void Station::set_identifier(const uint32_t &id) { dev_index_.value_ = id; }

}  // namespace wiphynlcontrol